import subprocess
import os
import glob
import pandas as pd


def run_prowler_check(check_id):
    print(f"Running Prowler check: {check_id}")

    result = subprocess.run(
        ["prowler", "aws", "-c", check_id],
        capture_output=True,
        text=True
    )

    print(result.stdout)

    

    # Find the newest CSV generated by Prowler
    csv_files = glob.glob("output/*.csv")

    if not csv_files:
        print("No Prowler CSV output found.")
        return None

    latest_csv = max(csv_files, key=os.path.getmtime)

    print("Reading:", latest_csv)

    df = pd.read_csv(latest_csv, sep=";")

    return df


if __name__ == "__main__":

    # Temporary test CHECK_ID
    check_id = input("Enter Prowler CHECK_ID: ").strip()

    df = run_prowler_check(check_id)

    if df is not None:
        print("\nRe-scan result:")
        print(
            df[
                ["CHECK_ID", "CHECK_TITLE", "STATUS", "RESOURCE_NAME"]
            ].to_string(index=False)
        )